"use client"
import { UserPlus, Target, Brain, TrendingUp } from 'lucide-react'
import Link from 'next/link'
import { useAuth } from '../../context/AuthProvider';

const HowItWorks = () => {
  const { user, logout, loading } = useAuth();

  const steps = [
    {
      icon: UserPlus,
      title: 'Sign Up',
      description: 'Create your account in seconds with our streamlined registration process',
      step: '01',
    },
    {
      icon: Target,
      title: 'Set Goals',
      description: 'Tell us your fitness objectives, preferences, and current fitness level',
      step: '02',
    },
    {
      icon: Brain,
      title: 'Get AI Plans',
      description: 'Receive personalized workout & meal plans generated by our advanced AI',
      step: '03',
    },
    {
      icon: TrendingUp,
      title: 'Track Progress',
      description: 'Monitor your transformation journey with detailed analytics and insights',
      step: '04',
    },
  ]

  return (
    <section id="how-it-works" className="py-10 sm:py-20 bg-maxfit-black">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8 sm:mb-16">
          <h2 className="text-2xl sm:text-4xl lg:text-5xl font-bold text-white mb-3 sm:mb-6">
            How <span className="text-[#B9E810] text-glow">it Works</span>
          </h2>
          <p className="text-sm sm:text-xl text-gray-300 max-w-3xl mx-auto">
            Get started with AI-powered fitness in just four simple steps
          </p>
        </div>

        <div className="relative">
          {/* Connection Line */}
          <div className="hidden lg:block absolute top-1/2 left-0 right-0 h-0.5 bg-gradient-to-r from-transparent via-maxfit-neon-green to-transparent transform -translate-y-1/2"></div>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-2 sm:gap-8">
            {steps.map((step, index) => (
              <div key={index} className="relative bg-gradient-to-br from-gray-900/20 to-gray-800/60  border border-maxfit-neon-green/30 px-2 sm:px-3 py-3 sm:py-4 rounded-xl sm:rounded-2xl text-center group">
                {/* Step Number */}
                <div className="relative z-10 mb-3 sm:mb-6">
                  <div className="w-14 h-14 sm:w-20 sm:h-20 bg-maxfit-neon-green/10 border-2 border-maxfit-neon-green rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4 group-hover:bg-maxfit-neon-green/20 transition-all duration-300">
                    <step.icon className="w-6 h-6 sm:w-8 sm:h-8 text-maxfit-neon-green" />
                  </div>
                </div>

                <h3 className="text-base sm:text-xl font-bold text-white mb-2 sm:mb-3 group-hover:text-maxfit-neon-green transition-colors duration-300">
                  {step.title}
                </h3>
                <p className=" text-xs sm:text-base text-gray-300 leading-relaxed">{step.description}</p>

                {/* Mobile Connection Arrow */}
                {index < steps.length - 1 && (
                  <div className="lg:hidden flex justify-center mt-4 sm:mt-8 mb-2 sm:mb-4">
                    <div className="w-0.5 h-4 sm:h-8 bg-maxfit-neon-green/50"></div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* CTA Section */}
        {!user && (
          <div className="text-center mt-10 sm:mt-20">
            <div className="bg-gradient-to-br from-gray-900/20 to-gray-800/60  border border-maxfit-neon-green/30 p-4 sm:p-8 rounded-xl sm:rounded-2xl max-w-2xl mx-auto">
              <h3 className="text-lg sm:text-2xl font-bold text-white mb-2 sm:mb-4">Ready to Transform Your Fitness?</h3>
              <p className="text-xs sm:text-base text-gray-300 mb-4 sm:mb-6">
                Join thousands of users who have already started their AI-powered fitness journey
              </p>
              <Link href="/signup">
                <button className="btn-neon px-6 sm:px-8 py-2 sm:py-3 rounded-lg text-sm sm:text-base font-semibold transition-all duration-300">
                  Get Started Now
                </button>
              </Link>
            </div>
          </div>
        )}
      </div>
    </section>
  )
}

export default HowItWorks
