/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    admins: AdminAuthOperations;
    coaches: CoachAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    admins: Admin;
    coaches: Coach;
    plans: Plan;
    'fitness-programs': FitnessProgram;
    'otp-verifications': OtpVerification;
    feedbacks: Feedback;
    recipes: Recipe;
    'workout-library': WorkoutLibrary;
    enrollments: Enrollment;
    conversations: Conversation;
    messages: Message;
    notifications: Notification;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    'fitness-programs': FitnessProgramsSelect<false> | FitnessProgramsSelect<true>;
    'otp-verifications': OtpVerificationsSelect<false> | OtpVerificationsSelect<true>;
    feedbacks: FeedbacksSelect<false> | FeedbacksSelect<true>;
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    'workout-library': WorkoutLibrarySelect<false> | WorkoutLibrarySelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Admin & {
        collection: 'admins';
      })
    | (Coach & {
        collection: 'coaches';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CoachAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  gender: string;
  plan: 'free' | 'proFit' | 'maxFlex';
  language: 'english' | 'arabic' | 'spanish' | 'french' | 'urdu';
  aiCallsUsed?: number | null;
  maxAiCalls?: number | null;
  minutesUsed?: number | null;
  emailVerified?: boolean | null;
  dodoSubscriptionId?: string | null;
  dodoCustomerId?: string | null;
  subscriptionStartDate?: string | null;
  subscriptionCanceledAt?: string | null;
  subscriptionEndDate?: string | null;
  subscriptionCanceled?: boolean | null;
  /**
   * Array of all previous AI plan contexts (full workout + diet details). Appended on each generation for paid users only.
   */
  lastPlanContext?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  profileImg?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  firstName: string;
  lastName: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: string;
  firstName: string;
  lastName: string;
  phone?: string | null;
  bio?: string | null;
  specializations?:
    | {
        specialization?: string | null;
        id?: string | null;
      }[]
    | null;
  yearsOfExperience?: number | null;
  certifications?:
    | {
        certification?: string | null;
        id?: string | null;
      }[]
    | null;
  profileImage?: string | null;
  /**
   * Inactive coaches cannot login
   */
  isActive?: boolean | null;
  /**
   * Calendly URL for booking sessions
   */
  calendlyUrl?: string | null;
  /**
   * Price per session in USD
   */
  pricePerSession?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: string;
  title: string;
  description: string;
  type: 'daily' | 'weekly' | 'monthly';
  /**
   * The coach who created this plan
   */
  coach: string | Coach;
  /**
   * e.g., "30 minutes", "1 hour", "4 weeks"
   */
  duration: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  /**
   * Price in USD (optional)
   */
  price?: number | null;
  isActive?: boolean | null;
  workouts?:
    | {
        /**
         * e.g., "Day 1", "Monday", "Week 1"
         */
        day: string;
        exercises?:
          | {
              name: string;
              sets?: number | null;
              reps?: string | null;
              duration?: string | null;
              rest?: string | null;
              notes?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  nutrition?: {
    calories?: string | null;
    protein?: string | null;
    carbs?: string | null;
    fats?: string | null;
    meals?:
      | {
          mealType?: ('breakfast' | 'lunch' | 'dinner' | 'snack') | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fitness-programs".
 */
export interface FitnessProgram {
  id: string;
  user: string;
  userDetails?: {
    age?: number | null;
    weight?: number | null;
    height?: string | null;
    fitnessGoals?: string | null;
    injuries?: string | null;
    fitnessLevel?: string | null;
    workoutDaysPerWeek?: number | null;
    dietaryRestrictions?: string | null;
  };
  workoutPlan:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dietPlan:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generatedAt?: string | null;
  status?: ('active' | 'archived' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-verifications".
 */
export interface OtpVerification {
  id: string;
  email: string;
  otp: string;
  verified?: boolean | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks".
 */
export interface Feedback {
  id: string;
  user: string | User;
  subject: string;
  rating: number;
  feedback: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: string;
  title?: string | null;
  category?:
    | (
        | 'High Protein Meals'
        | 'Protein Snacks'
        | 'Breakfast'
        | 'Smoothies & Drinks'
        | 'Vegetarian Meals'
        | 'Gluten-Free Meals'
        | 'Healthy Desserts'
        | 'Quick & Easy Meals'
      )
    | null;
  ingredients?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  prep_minutes?: number | null;
  imgUrl?: string | null;
  macros?: {
    kcal?: number | null;
    protein?: number | null;
    carbs?: number | null;
    fat?: number | null;
  };
  steps?:
    | {
        step?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-library".
 */
export interface WorkoutLibrary {
  id: string;
  title: string;
  description?: string | null;
  coach: string | Coach;
  contentType: 'youtube' | 'tiktok' | 'instagram';
  /**
   * URL to the video content
   */
  videoUrl: string;
  /**
   * Optional custom thumbnail URL
   */
  thumbnailUrl?: string | null;
  category?: ('strength' | 'cardio' | 'yoga' | 'hiit' | 'nutrition' | 'recovery' | 'mobility' | 'other') | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Make visible to clients
   */
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: string;
  /**
   * The user who is enrolling
   */
  user: string | User;
  /**
   * The coach whose plan the user is enrolling in
   */
  coach: string | Coach;
  /**
   * The plan the user is enrolling in
   */
  plan: string | Plan;
  /**
   * Status of the enrollment request
   */
  status: 'pending' | 'accepted' | 'rejected';
  paymentStatus: 'pending' | 'paid' | 'failed';
  /**
   * Optional notes from the user
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  /**
   * The user in this conversation
   */
  user: string | User;
  /**
   * The coach in this conversation
   */
  coach: string | Coach;
  /**
   * The enrollment that triggered this conversation
   */
  enrollment?: (string | null) | Enrollment;
  /**
   * Preview of the last message
   */
  lastMessage?: string | null;
  /**
   * When the last message was sent
   */
  lastMessageAt?: string | null;
  /**
   * Unread count for user
   */
  userUnreadCount?: number | null;
  /**
   * Unread count for coach
   */
  coachUnreadCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  /**
   * The conversation this message belongs to
   */
  conversation: string | Conversation;
  /**
   * Who sent this message
   */
  sender:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'coaches';
        value: string | Coach;
      };
  /**
   * Message content
   */
  content: string;
  /**
   * Whether the message has been read
   */
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  /**
   * Who this notification is for
   */
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'coaches';
        value: string | Coach;
      };
  /**
   * Type of notification
   */
  type: 'enrollment_request' | 'enrollment_accepted' | 'enrollment_rejected' | 'new_message';
  /**
   * Notification title
   */
  title: string;
  /**
   * Notification message
   */
  message: string;
  /**
   * ID of related entity (enrollment, conversation, etc.)
   */
  relatedId?: string | null;
  /**
   * Whether the notification has been read
   */
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'coaches';
        value: string | Coach;
      } | null)
    | ({
        relationTo: 'plans';
        value: string | Plan;
      } | null)
    | ({
        relationTo: 'fitness-programs';
        value: string | FitnessProgram;
      } | null)
    | ({
        relationTo: 'otp-verifications';
        value: string | OtpVerification;
      } | null)
    | ({
        relationTo: 'feedbacks';
        value: string | Feedback;
      } | null)
    | ({
        relationTo: 'recipes';
        value: string | Recipe;
      } | null)
    | ({
        relationTo: 'workout-library';
        value: string | WorkoutLibrary;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: string | Enrollment;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'coaches';
        value: string | Coach;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'coaches';
        value: string | Coach;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  gender?: T;
  plan?: T;
  language?: T;
  aiCallsUsed?: T;
  maxAiCalls?: T;
  minutesUsed?: T;
  emailVerified?: T;
  dodoSubscriptionId?: T;
  dodoCustomerId?: T;
  subscriptionStartDate?: T;
  subscriptionCanceledAt?: T;
  subscriptionEndDate?: T;
  subscriptionCanceled?: T;
  lastPlanContext?: T;
  profileImg?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  bio?: T;
  specializations?:
    | T
    | {
        specialization?: T;
        id?: T;
      };
  yearsOfExperience?: T;
  certifications?:
    | T
    | {
        certification?: T;
        id?: T;
      };
  profileImage?: T;
  isActive?: T;
  calendlyUrl?: T;
  pricePerSession?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  coach?: T;
  duration?: T;
  difficulty?: T;
  price?: T;
  isActive?: T;
  workouts?:
    | T
    | {
        day?: T;
        exercises?:
          | T
          | {
              name?: T;
              sets?: T;
              reps?: T;
              duration?: T;
              rest?: T;
              notes?: T;
              id?: T;
            };
        id?: T;
      };
  nutrition?:
    | T
    | {
        calories?: T;
        protein?: T;
        carbs?: T;
        fats?: T;
        meals?:
          | T
          | {
              mealType?: T;
              description?: T;
              id?: T;
            };
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fitness-programs_select".
 */
export interface FitnessProgramsSelect<T extends boolean = true> {
  user?: T;
  userDetails?:
    | T
    | {
        age?: T;
        weight?: T;
        height?: T;
        fitnessGoals?: T;
        injuries?: T;
        fitnessLevel?: T;
        workoutDaysPerWeek?: T;
        dietaryRestrictions?: T;
      };
  workoutPlan?: T;
  dietPlan?: T;
  generatedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-verifications_select".
 */
export interface OtpVerificationsSelect<T extends boolean = true> {
  email?: T;
  otp?: T;
  verified?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks_select".
 */
export interface FeedbacksSelect<T extends boolean = true> {
  user?: T;
  subject?: T;
  rating?: T;
  feedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  ingredients?:
    | T
    | {
        name?: T;
        id?: T;
      };
  prep_minutes?: T;
  imgUrl?: T;
  macros?:
    | T
    | {
        kcal?: T;
        protein?: T;
        carbs?: T;
        fat?: T;
      };
  steps?:
    | T
    | {
        step?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-library_select".
 */
export interface WorkoutLibrarySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  coach?: T;
  contentType?: T;
  videoUrl?: T;
  thumbnailUrl?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  user?: T;
  coach?: T;
  plan?: T;
  status?: T;
  paymentStatus?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  user?: T;
  coach?: T;
  enrollment?: T;
  lastMessage?: T;
  lastMessageAt?: T;
  userUnreadCount?: T;
  coachUnreadCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  sender?: T;
  content?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  message?: T;
  relatedId?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}